FileVersion = 1
Dependencies = {corlib = "*", SDL2 = "*", raylib-beef = "*"}

[Project]
Name = "SpaceGameEngine"
TargetType = "BeefLib"
StartupObject = "SpaceGameEngine.Program"

[Configs.Debug.Win64]
PreprocessorMacros = ["DEBUG", "ENGINE_RAYLIB"]
