FileVersion = 1
Projects = {SpaceGame = {Path = "."}, SDL2 = "*", SpaceGameEngine = {Path = "SpaceGameEngine"}, raylib-beef = {Path = "vendor/raylib-beef"}}
Unlocked = ["SDL2"]
ExtraPlatforms = ["wasm32"]

[Workspace]
StartupProject = "SpaceGame"
