FileVersion = 1
Projects = {SpaceGame = {Path = "."}, SDL2 = "*", SpaceGameEngine = {Path = "SpaceGameEngine"}}
Unlocked = ["SDL2"]
ExtraPlatforms = ["wasm32"]

[Workspace]
StartupProject = "SpaceGame"
